package com.credify.investor.act.domain;

public enum FileType {
    INVESTMENT_ACCOUNT,
    BANK_ACCOUNT,
    ACCOUNT_CONFIG,
    ALLOCATION_CONFIG,
    CASH_SWEEP_CONFIG,
    MEMBERIZATION_REQUIREMENTS,
    PURCHASE_PRICE_CONFIG
}
